[package]
name = "CedraBridgeDev"
version = "0.0.1"

[addresses]
cedra_framework = "0x1"
bridge = "0xd3c57dc714d710126e74bba9b7607dab714afb837474b3f451c4110ea8ad8318"  # <-- multisig

[dependencies]
CedraFramework = { local = "../cedra-move/framework/cedra-framework" } 