# This defines a workflow to build and release a new version of the cedra Node.
# In order to trigger it go to the Actions Tab of the Repo, click "Release Node" and then "Run Workflow".

name: "Release Node"

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        required: true
        description: "The release version. E.g. `0.2.3`:"
      source_git_ref_override:
        type: string
        required: false
        description: "GIT_SHA_OVERRIDE: Use this to override the Git SHA1, branch name (e.g. devnet) or tag to build the binaries from. Defaults to the workflow Git REV, but can be different than that:"
      dry_run:
        type: boolean
        required: false
        default: true
        description: "Dry run - If checked, the release will not be created"


jobs:
  # TODO: Deprecated, please use "Linux" instead as it's more straightforwardly named
  build-ubuntu22-binary:
    name: "Build Ubuntu 22.04 binary"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.source_git_ref_override }}
      - uses: cedra-labs/cedra-network/.github/actions/node-rust-setup@main
      - name: Build Node
        run: scripts/node/build_nocde_release.sh "Ubuntu-22.04" "${{inputs.release_version}}" "false"
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: node-builds-ubuntu-22.04
          path: cedra-node-*.zip

  # Add one for 24.04 to be clear
  build-ubuntu24-binary:
    name: "Build Ubuntu 24.04 binary"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.source_git_ref_override }}
      - uses: cedra-labs/cedra-network/.github/actions/node-rust-setup@main
      - name: Build Node
        run: scripts/node/build_node_release.sh "Ubuntu-24.04" "${{inputs.release_version}}" "false"
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: node-builds-ubuntu-24.04
          path: cedra-node-*.zip

  # Generic linux should be the older version, more likely compatible
  # This actually builds for non-SIMD processors, and an older GLIBC
  # TODO: Possibly find a way to support a baseline GLIBC rather than just whatever is on 22.04
  build-linux-binary:
    name: "Build Linux binary"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.source_git_ref_override }}
      - uses: cedra-labs/cedra-network/.github/actions/node-rust-setup@main
      - name: Build Node
        run: scripts/node/build_node_release.sh "Linux" "${{inputs.release_version}}" "true"
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: node-builds-linux
          path: cedra-node-*.zip

  # Generic linux arm should be the older version, more likely compatible
  build-linux-arm-binary:
    name: "Build Linux ARM binary"
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.source_git_ref_override }}
      - uses: cedra-labs/cedra-network/.github/actions/node-rust-setup@main
      - name: Build Node
        run: scripts/node/build_node_release.sh "Linux" "${{inputs.release_version}}" "false"
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: node-builds-linux-arm
          path: cedra-node-*.zip

  build-macos-x86_64-binary:
    name: "Build MacOS x86_64 binary"
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.source_git_ref_override }}
      - uses: cedra-labs/cedra-network/.github/actions/node-rust-setup@main
      - name: Build Node
        run: scripts/node/build_node_release.sh "macOS" "${{inputs.release_version}}" "false"
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: node-builds-macos-x86-64
          path: cedra-node-*.zip

  build-macos-arm-binary:
    name: "Build MacOS ARM binary"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.source_git_ref_override }}
      - uses: cedra-labs/cedra-network/.github/actions/node-rust-setup@main
      - name: Build Node
        run: scripts/node/build_node_release.sh "macOS" "${{inputs.release_version}}" "false"
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: node-builds-macos-arm
          path: cedra-node-*.zip

  build-windows-binary:
    name: "Build Windows binary"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.source_git_ref_override }}
      # Ensure that long paths work
      - name: Ensure long paths work
        run: git config --global core.longpaths true
        shell: bash
      - name: Build Node
        run: scripts\node\build_node_release.ps1
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: node-builds-windows
          path: cedra-node-*.zip

  release-binaries:
    name: "Release binaries"
    needs:
      - build-ubuntu22-binary
      - build-ubuntu24-binary
      - build-windows-binary
      - build-linux-binary
      - build-linux-arm-binary
      - build-macos-arm-binary
      - build-macos-x86_64-binary
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      pull-requests: "read"
    if: ${{ inputs.dry_run }} == 'false'
    steps:
      - name: Download prebuilt binaries
        uses: actions/download-artifact@v4
        with:
          pattern: node-builds-*
          merge-multiple: true
      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # pin@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ format('cedra-node-v{0}', inputs.release_version) }}"
          prerelease: false
          title: "${{ format('Cedra Node Release v{0}', inputs.release_version) }}"
          files: |
            cedra-node-*.zip
